In [1]:
import pandas as pd
import numpy as np
import math

In [2]:
pibpc_df = pd.read_excel("Tabela_pib_per_capita_brasileiro.xlsx")

In [3]:
display(pibpc_df)

     Ano  PIB per capita-valores correntes (Reais)
0   1996                                   5219.36
1   1997                                   5729.02
2   1998                                   5944.92
3   1999                                   6359.80
4   2000                                   6900.62
5   2001                                   7467.03
6   2002                                   8340.58
7   2003                                   9506.76
8   2004                                  10705.99
9   2005                                  11733.45
10  2006                                  12880.52
11  2007                                  14390.01
12  2008                                  16280.82
13  2009                                  17271.34
14  2010                                  19938.60
15  2011                                  22259.91
16  2012                                  24278.35
17  2013                                  26657.54
18  2014                                  28648.74
19  2015                                  29466.85
20  2016                                  30558.75
21  2017                                  31843.95
22  2018                                  33593.82
23  2019                                  35161.70
24  2020                                  35935.69

In [5]:
pibpc_df["xy"] = pibpc_df['Ano'] * pibpc_df['PIB per capita-valores correntes (Reais)']

In [6]:
display(pibpc_df)

     Ano  PIB per capita-valores correntes (Reais)           xy
0   1996                                   5219.36  10417842.56
1   1997                                   5729.02  11440852.94
2   1998                                   5944.92  11877950.16
3   1999                                   6359.80  12713240.20
4   2000                                   6900.62  13801240.00
5   2001                                   7467.03  14941527.03
6   2002                                   8340.58  16697841.16
7   2003                                   9506.76  19042040.28
8   2004                                  10705.99  21454803.96
9   2005                                  11733.45  23525567.25
10  2006                                  12880.52  25838323.12
11  2007                                  14390.01  28880750.07
12  2008                                  16280.82  32691886.56
13  2009                                  17271.34  34698122.06
14  2010                                  19938.60  40076586.00
15  2011                                  22259.91  44764679.01
16  2012                                  24278.35  48848040.20
17  2013                                  26657.54  53661628.02
18  2014                                  28648.74  57698562.36
19  2015                                  29466.85  59375702.75
20  2016                                  30558.75  61606440.00
21  2017                                  31843.95  64229247.15
22  2018                                  33593.82  67792328.76
23  2019                                  35161.70  70991472.30
24  2020                                  35935.69  72590093.80

In [8]:
pibpc_df['ln Ano'] = pibpc_df['Ano'].apply(math.log1p)

In [9]:
display(pibpc_df)

     Ano  PIB per capita-valores correntes (Reais)           xy    ln Ano
0   1996                                   5219.36  10417842.56  7.599401
1   1997                                   5729.02  11440852.94  7.599902
2   1998                                   5944.92  11877950.16  7.600402
3   1999                                   6359.80  12713240.20  7.600902
4   2000                                   6900.62  13801240.00  7.601402
5   2001                                   7467.03  14941527.03  7.601902
6   2002                                   8340.58  16697841.16  7.602401
7   2003                                   9506.76  19042040.28  7.602900
8   2004                                  10705.99  21454803.96  7.603399
9   2005                                  11733.45  23525567.25  7.603898
10  2006                                  12880.52  25838323.12  7.604396
11  2007                                  14390.01  28880750.07  7.604894
12  2008                                  16280.82  32691886.56  7.605392
13  2009                                  17271.34  34698122.06  7.605890
14  2010                                  19938.60  40076586.00  7.606387
15  2011                                  22259.91  44764679.01  7.606885
16  2012                                  24278.35  48848040.20  7.607381
17  2013                                  26657.54  53661628.02  7.607878
18  2014                                  28648.74  57698562.36  7.608374
19  2015                                  29466.85  59375702.75  7.608871
20  2016                                  30558.75  61606440.00  7.609367
21  2017                                  31843.95  64229247.15  7.609862
22  2018                                  33593.82  67792328.76  7.610358
23  2019                                  35161.70  70991472.30  7.610853
24  2020                                  35935.69  72590093.80  7.611348

In [10]:
pibpc_df.to_excel('test.xlsx')